services:
  db:
    image: postgres:15
    container_name: crags_db
    restart: always

    environment:
      POSTGRES_DB: Crags_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ABC123

    ports:
      - "5432:5432"

    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/01-dump.sql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build: .
    container_name: crags_web
    restart: always

    ports:
      - "5000:5000"

    environment:
      DB_NAME: Crags_db
      DB_USER: postgres
      DB_PW: ABC123
      DB_HOST: db

    depends_on:
      db:
        condition: service_healthy